version: '2'

services:
  myapp:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    env_file:
      - .env
